movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from . models import Movie
from . forms import MovieForm

# Create your views here.

def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list': movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render (request,"add.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form . is_valid():
        form.save()
        return redirect('/')
    return render (request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name"><br>
    <input type="text" name="desc" placeholder="Write something about the movie"><br>
    <input type="text" name="year" placeholder="Enter the year of release"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-md">
          <a class="navbar-brand" href="#">Movie Store</a>
          <button type="button" class="btn btn-warning"><a href="{% url 'movieapp:add_movie' %}">Add movie</a></button>
        </div>
      </nav>
      <br>
      {% block body %}
      {% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    <p>Delete this movie?</p>
    <input type="submit" value="Delete">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="250" height="300"> 
        </div>
        <div class="col-md-6">
            {{movie.name}} <br>
            {{movie.desc}} <br>
            {{movie.year}} <br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>
</div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
          <div class="card" style="width: 17rem;"> 
            <img  class="card-img-top" src="{{i.img.url}}" width="200px" height="350px">
              <div class="card-body"> 
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">{{i.desc}}</p>
                <button type="button" class="btn btn-info"><a href="{% url 'movieapp:detail' i.id %}">More info</a></button>
              </div>
          </div>
        </div>
        <br>
        {% endfor %}
    </div>
</div>
{% endblock %}
